"""
Build script for Wizard of Wor LAN.

    python tools/build.py            build everything
    python tools/build.py run        build and start the PRG in VICE
    python tools/build.py shot [N]   build, run N million cycles in VICE (warp) and save a screenshot

64tass runs inside WSL (tools/64tass.sh fetches it on first use).
VICE is taken from the VICE_DIR environment variable or the default path below.
"""
from __future__ import annotations

import hashlib
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
BUILD = os.path.join(ROOT, "build")
VICE_DIR = os.environ.get("VICE_DIR", r"C:\Users\user\OneDrive\dev\c64\vice\bin")
WSL_DISTRO = os.environ.get("WSL_DISTRO", "Ubuntu-24.04")

# md5 of the unmodified upstream source assembled as a cartridge
# the cartridge build must keep matching this as long as all NET changes are PRG-only
BASELINE_CART_MD5 = "c2c674a27896a389ff31cc0bb42292fc"


def tass(*args: str) -> None:
    """Run 64tass in WSL with the project root as working directory (paths relative, forward slashes)."""
    cmd = ["wsl", "-d", WSL_DISTRO, "--", "bash", "tools/64tass.sh", "-q", *args]
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if r.returncode != 0:
        print(out)
        sys.exit(f"64tass failed: {' '.join(args)}")
    if out:
        print(out)


CC65_BIN = os.environ.get("CC65_BIN", r"C:\Users\user\OneDrive\dev\c64\cc65\bin")
CC65_ASMINC = os.path.join(os.path.dirname(CC65_BIN), "asminc")
IP65_DIR = os.path.join(ROOT, "third_party", "ip65")
IP65_SOURCES = [os.path.join("ip65", f) for f in sorted(os.listdir(os.path.join(IP65_DIR, "ip65")))] + \
    [os.path.join("drivers", f) for f in ("rr-net.s", "cs8900adriver.s", "ethernet.s")]


def cc65(tool: str, *args: str) -> None:
    r = subprocess.run([os.path.join(CC65_BIN, tool + ".exe"), *args], cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        print((r.stdout + r.stderr).strip())
        sys.exit(f"{tool} failed")


def build_ip65_lib() -> str:
    """Assembles the vendored ip65 UDP stack + RR-Net driver into build/ip65/ip65.lib (once)."""
    out = os.path.join(BUILD, "ip65")
    os.makedirs(out, exist_ok=True)
    lib = os.path.join(out, "ip65.lib")
    srcs = [os.path.join(IP65_DIR, s) for s in IP65_SOURCES]
    if os.path.exists(lib) and all(os.path.getmtime(s) < os.path.getmtime(lib) for s in srcs):
        return lib
    objs = []
    for s in srcs:
        o = os.path.join(out, os.path.splitext(os.path.basename(s))[0] + ".o")
        cc65("ca65", "-I", CC65_ASMINC, "-o", o, s)
        objs.append(o)
    if os.path.exists(lib):
        os.remove(lib)
    cc65("ar65", "a", lib, *objs)
    return lib


def build_ip65_blob(name: str, start: int, zp: int) -> None:
    """Links the ip65 blob for a given address and zero page base and writes a 64tass include
    (build/<name>.inc) with every label inside an 'ip65' block."""
    lib = build_ip65_lib()
    glue_o = os.path.join(BUILD, "ip65", "ip65_glue.o")
    cc65("ca65", "-I", CC65_ASMINC, "-o", glue_o, "src/net/ip65_glue.s")
    binf = os.path.join(BUILD, name + ".bin")
    lbl = os.path.join(BUILD, name + ".lbl")
    cc65("ld65", "-C", "src/net/ip65_blob.cfg", "-D", f"__BLOBADDR__=${start:04X}", "-D", f"__ZPADDR__=${zp:02X}",
         "-o", binf, "-Ln", lbl, "-m", os.path.join(BUILD, name + ".map"), glue_o, lib)
    syms = {}
    with open(lbl) as f:
        for line in f:
            parts = line.split()
            if len(parts) == 3 and parts[2].startswith(".") and parts[2][1:].replace("_", "a").isalnum():
                syms.setdefault(parts[2][1:], int(parts[1], 16))
    with open(os.path.join(BUILD, name + ".inc"), "w", newline="\n") as f:
        f.write(f"; generated by tools/build.py from {name}.lbl - do not edit\n")
        f.write(f"IP65_BLOB_START = ${start:04X}\nIP65_BLOB_SIZE = {os.path.getsize(binf)}\n")
        f.write(f"IP65_BSS_END = ${syms.get('__BSS_RUN__', start) + syms.get('__BSS_SIZE__', 0):04X}\n")
        f.write("ip65 .block\n")
        for k, v in sorted(syms.items()):
            if not k.startswith("__"):
                f.write(f"{k} = ${v:04X}\n")
        f.write(".bend\n")
    print(f"ip65 blob       : build/{name}.bin ({os.path.getsize(binf)} bytes at ${start:04X}, zp ${zp:02X})")


def md5(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()


def vice(name: str) -> str:
    return os.path.join(VICE_DIR, name)


def build() -> None:
    os.makedirs(BUILD, exist_ok=True)

    # 1. original cartridge layout - regression check against the upstream binary
    tass("-a", "src/wizard_of_wor.asm", "-b", "-o", "build/wow_cart.bin",
         "-L", "build/wow_cart.lst", "-l", "build/wow_cart.lbl")
    cart_md5 = md5(os.path.join(BUILD, "wow_cart.bin"))
    if cart_md5 == BASELINE_CART_MD5:
        print("cartridge build : identical to upstream")
    else:
        print(f"cartridge build : DIFFERS from upstream ({cart_md5})")
    subprocess.run([vice("cartconv.exe"), "-i", "build/wow_cart.bin", "-o", "build/wow_cart.crt",
                    "-t", "normal", "-n", "WIZARD OF WOR"], cwd=ROOT, check=True, capture_output=True)

    # 2. RAM based version packed into a PRG
    build_game("wow")

    # 3. network measurement program (phase 0)
    tass("-a", "src/net/nettest.asm", "-o", "build/nettest.prg", "-L", "build/nettest.lst",
         "-l", "build/nettest.lbl", "--vice-labels")
    print(f"nettest (UCI)   : build/nettest.prg ({os.path.getsize(os.path.join(BUILD, 'nettest.prg'))} bytes)")
    build_ip65_blob("ip65_nettest", 0x2000, 0x50)
    tass("-a", "-D", "NET_RRNET=1", "src/net/nettest.asm", "-o", "build/nettest_rrnet.prg",
         "-L", "build/nettest_rrnet.lst", "-l", "build/nettest_rrnet.lbl", "--vice-labels")
    print(f"nettest (RRNET) : build/nettest_rrnet.prg ({os.path.getsize(os.path.join(BUILD, 'nettest_rrnet.prg'))} bytes)")

    # 4. disk image
    d64 = os.path.join(BUILD, "wow.d64")
    if os.path.exists(d64):
        os.remove(d64)
    subprocess.run([vice("c1541.exe"), "-format", "wizard of wor,wl", "d64", "build/wow.d64",
                    "-write", "build/wow.prg", "wow", "-write", "build/nettest.prg", "nettest", "-write", "build/nettest_rrnet.prg", "nettest-rrnet"],
                   cwd=ROOT, check=True, capture_output=True)
    print("disk image      : build/wow.d64")


def build_game(name: str, *defines: str, check: bool = True) -> None:
    """Assembles the PRG version (TARGET_PRG=1 plus extra -D defines) into build/<name>.prg."""
    args = ["-a", "-D", "TARGET_PRG=1"]
    for d in defines:
        args += ["-D", d]
    tass(*args, "src/wizard_of_wor.asm", "-b", "-o", "build/wow_payload.bin",
         "-L", f"build/{name}.lst", "-l", f"build/{name}.lbl", "--vice-labels")
    if check:
        layout_check(f"build/{name}.lbl")
    tass("-a", "src/loader.asm", "-o", f"build/{name}.prg")
    print(f"PRG             : build/{name}.prg ({os.path.getsize(os.path.join(BUILD, name + '.prg'))} bytes)"
          + (f"  [{' '.join(defines)}]" if defines else ""))


def layout_check(lblfile: str = "build/wow.lbl") -> None:
    """The PRG image must keep the layout of the original 16K image: only same-size patches are allowed there.
    (The sprite data block contains code, so any shift silently corrupts sprites.)"""
    with open(os.path.join(BUILD, "wow_cart.bin"), "rb") as f:
        cart = f.read()
    with open(os.path.join(BUILD, "wow_payload.bin"), "rb") as f:
        prg = f.read()[:len(cart)]
    ranges: list[list[int]] = []
    for i, (a, b) in enumerate(zip(cart, prg)):
        if a != b:
            if ranges and i - ranges[-1][1] <= 4:
                ranges[-1][1] = i
            else:
                ranges.append([i, i])
    labels = {}
    with open(os.path.join(ROOT, lblfile)) as f:
        for line in f:
            parts = line.split()
            if len(parts) == 3:
                labels.setdefault(int(parts[1], 16), parts[2].lstrip("."))
    def near(addr: int) -> str:
        best = max((a for a in labels if a <= addr), default=None)
        return f"{labels[best]}+{addr - best}" if best is not None else "?"
    print(f"layout check    : {len(ranges)} patched area(s) in the original image")
    for lo, hi in ranges:
        print(f"                  ${0x8000 + lo:04X}-${0x8000 + hi:04X}  {near(0x8000 + lo)}")
    if len(ranges) > 40:
        sys.exit("layout check: too many differences - something shifted the original layout")


def run() -> None:
    subprocess.Popen([vice("x64sc.exe"), "-autostart", os.path.join(BUILD, "wow.prg"), "+confirmonexit"],
                     cwd=ROOT)


def shot(mcycles: int) -> str:
    png = os.path.join(BUILD, "shot.png")
    if os.path.exists(png):
        os.remove(png)
    subprocess.run([vice("x64sc.exe"), "-default", "-sounddev", "dummy", "-warp",
                    "-limitcycles", str(mcycles * 1_000_000), "-exitscreenshot", png,
                    "-autostart", os.path.join(BUILD, "wow.prg")],
                   cwd=ROOT, capture_output=True, timeout=300)
    print(f"screenshot      : {png}")
    return png


if __name__ == "__main__":
    build()
    action = sys.argv[1] if len(sys.argv) > 1 else ""
    if action == "profile":
        build_game("wow_profile", "PROFILE=1", check=False)
    elif action == "dettest":
        build_game("wow_dettest", "DETTEST=1", check=False)
        build_game("wow_dettest_fast", "DETTEST=1", "DETTEST_FAST=1", check=False)
    elif action == "speedtest":
        build_game("wow_speedtest", "DETTEST=1", "SPEEDTEST=1", check=False)
    elif action == "run":
        run()
    elif action == "shot":
        shot(int(sys.argv[2]) if len(sys.argv) > 2 else 60)
